### ISSUE TITLE
AOT Compiling issues when following example app (entity state reducer)

### ISSUE THREAD

**Issue by mxdmedia** [briebug/ngrx-auto-entity-docs#2]
In the documentation, specifically in the Example Application --> Entity State section, the reducers are created as follows:

```typescript
export const orderReducer = createReducer(initialState);
```

After following this section to build a sample app, and trying to compile using AOT, the build fails for each AE entity's reducer.  Reviewing the docs in the "From Scratch" section, reducers are build like this:

```typescript
export function customerReducer(state = initialState): IEntityState<Customer> {
  return state;
}
```

After updating my code to export a function in this way, AOT compiling works fine.  Therefore, I propose updating the Example App docs to reflect this.  PR incoming.

**Comment by jrista** [comment]
So, when you use the new NgR 8 createReducer function, you get an AOT error?

**Comment by mxdmedia** [comment]
Sort of.  It isn't specifically an "AOT" error, but rather the error is only thrown if AOT is enabled..  Give the following entity state:

```typescript
import { buildState, IEntityState } from '@briebug/ngrx-auto-entity';
import { createReducer } from '@ngrx/store';
import { SnippetLanguage } from '../models';

export const {
  initialState: snippetLanguageInitialState,
  selectors: snippetLanguageSelectors,
  facade: SnippetLanguageFacadeBase
} = buildState(SnippetLanguage);

// export function snippetLanguageReducer(state = snippetLanguageInitialState): IEntityState<SnippetLanguage> {
//   return state;
// }

export const snippetLanguageReducer = createReducer(snippetLanguageInitialState);
```

If I do a simple `ng serve` everything works fine.  Once I attempt to do: `ng build --prod` I get the following error:

```
ERROR in src/app/state/snippet-language.state.ts(15,39): Error during template compile of 'snippetLanguageReducer'
  Function calls are not supported in decorators but 'createReducer' was called.
```

The two ways I can fix this- 1) disable AOT in my production build, or 2) use the commented out reducer function rather than using the ngrx8 createReducer function.  If I do either of these it compiles fine, which led me to believe it has something to do with AOT.

**Comment by jrista** [comment]
Ah! Yeah, if you need to use something inside of a decorator, you cannot create it dynamically. It needs to be statically created. I wonder if this is a problem in general with the new ngrx8 creator functions... By calling createReducer, you are dynamically creating a reducer, rather than statically creating it. So you couldn't plug that reducer, ultimately, into the @NgModule directive when you pass the reducer map to StoreModule.forRoot(...). 

I'll see if there is a best practice here. If this is an issue with ngrx 8, then people must have run into it already and there must be some kind of resolution for it.

**Comment by jrista** [comment]
BTW, this is the reason why, even though I do generate a reducer function for you when you call buildState(), you cannot actually use it in any production app. Because my reducer function, much like that returned by createReducer, is dynamic not static.

**Comment by jrista** [comment]
Well, it looks like you just cannot use createReducer like they probably intended it to be used. I think people are doing this:

```typescript
const _customerReducer = createReducer(initialState, /* ... handle cases here ... */);
export function customerReducer(state = initialState, action: EntityActions<Customer>): IEntityState<Customer> {
  return _customerReducer(state, action);
}
```

So, in an Auto-Entity context...it really isn't going to help you much. I don't see, at least as things are now with Auto-Entity, bothering with `createReducer`. I'll fix the docs this weekend.

**Comment by jrista** [comment]
Thanks for the report, @mxdmedia. I've updated the docs with your PR.
